spring:
  profiles:
    active: @spring.profiles.active@
  datasource:
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/coworking
          username: postgres
          password: 12345

  jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          ddl-auto: update
          hbm2ddl:
            auto: update

